### PR TITLE
Dynamic Redirect URL

### PR DESCRIPTION
**Pull request by ashleighsims**
Issue: #10 

Addition of a dynamic redirect url capabilities.

### CODE REVIEW

**Comment by edgrosvenor** [comment]
@ashleighsims This is a great start! A couple thoughts:

It looks, unless I'm missing something, like you're requiring the redirect to correspond to a named route. While I'm a huge fan of named routes and I think people should definitely get in the habit of using them, it's a pretty limiting restriction. I can think of some edge cases where it would cause trouble for me.

I assume the reason that you are looking for a named route is that you want to ensure that the redirect url actually exists so that users aren't getting logged in and then thrown to a 404. That's actually a consideration I would have missed had I addressed this myself, so I'm glad you did what you did. I just want to think through how we can try to accomplish this without being too overly restrictive.

The only other thing I think I'd do differently is instead of passing the redirect URL to the generate() method as a parameter, I'd make the redirect url a property on the class and use a setter. It just doesn't feel totally intuitive to have a redirect url as the sole parameter on that method, even though I think that's how it was drawn up in the original issue.

Thanks for what you've done so far. It gets us most of the way to closing that issue and making a big improvement to the package! As for the tests, I'll add some before we merge this in and talk you through what I tested and why.

**Comment by hariadi** [comment]
I think better like:
```php
public function generate($redirectUrl = null)
{
    if ($this->isAuthenticatable()) {
        return URL::temporarySignedRoute(
            $this->route_name, $this->route_expires, array_filter([
                'uid' => $this->user->id,
                'intended' => $redirectUrl,
            ])
        );
    }
}
```

So in the routes,

```php
$redirectOnSuccessTo = $request->filled('intended')
    ? $request->intended
    : config('laravel-passwordless-login.redirect_on_success');

redirect($redirectOnSuccessTo);
```

**Comment by innoflash** [comment]
How about we use a trait like `PasswordlessLogable` where we set the defaults in. 

Imagine we can have multiple users they can use different:

- Guard
- Login URL
- Remember login
- prettry much all in the config

But in the trait we set the defaults to everything in the config and give users the chance to overwrite a setup they want

**Comment by edgrosvenor** [comment]
@innoflash I think I like the trait idea. What would the config actually look like though. Ideally I’d like to keep people from having to publish a config file. But if we can make it easy via a few environment variables with some good defaults out of the box I like it.

**Comment by innoflash** [comment]
@edgrosvenor yeah sounds like a plan there, we can either make the properties of the the trait abstract if we wanna avoid the config and documenting about default environment variables.

Or better yet, we can just set the defaults in the trait and users override as per need

**Comment by edgrosvenor** [comment]
@innoflash and @ashleighsims - Here's how I think we should wrap this up.

- [ ] Remove $redirectUrl as a parameter to the generate() method and create a setRedirectUrl() method instead to override the default redirect URL.

- [ ] Remove the requirement that the redirect URL be a named route and just trust that the user is sending a valid URL. Unless someone can think of a very fast, efficient way to validate that a URL maps to a good route even if it's not a named route. Then I'm open to validation.

- [ ] @innoflash In a separate PR, can you create the trait discussed? I think we keep the configuration as is, let the user set a redirect url for a user type in a trait, and let the developer override via setRedirectUrl(). So setRedirectUrl() sets a url if used, the trait url is used if not, and if no trait url is set, use the default configured url.

- [ ] In yet another PR, let's figure out the best way to encode the authenticatable model used in the link itself so that we aren't limiting developers to a single user model type. Maybe we leave the default in the configuration and allow for it to be overridden with ?user_type=app_models_managers or something.

- [ ] I will take care of catching up the test coverage so that everything here and everything that's been added without tests is covered.

Thoughts?

**Comment by innoflash** [comment]
Yeap according to me that sounds like a plan, will work on the PR assigned to me later.

> In yet another PR, let's figure out the best way to encode the authenticatable model used in the link itself so that we aren't limiting developers to a single user model type. 

On this one i think after the trait we might win because we will allow users to define auth guards and that way its possible to do multi-model login (theoretically :))

**Comment by ashleighsims** [comment]
Sounds like a plan. I’ll get cracking on with the bits assigned to me.

**Comment by ashleighsims** [comment]
From looking at the docs, the temporarySignedRoute requires a named route be provided as the first argument.

**Comment by edgrosvenor** [comment]
@ashleighsims That's true, but the first argument is the URL to the route that actually does the authentication. That should always be the route that the package provides because it does the actual logging in based on what it finds on the URL. The redirect URL should just be an additional parameter on the link that can, but doesn't have to be a named route. 

What we're going for here is something like this:

```
return URL::temporarySignedRoute(
            $this->route_name, // Always the login route to the package
            $this->route_expires,
            [
                'uid' => $this->user->id,
                'url' => $redirectUrl, // <-- This is the redirect URL
            ]
        );
```

Then after the package's login controller authenticates the user, they should be redirected to $redirectUrl.

**Comment by edgrosvenor** [comment]
@ashleighsims Great work! Don't sweat the styleci issues. I'll handle that when I rebase and merge this in. There are conflicts I need to resolve anyway.

**Comment by ashleighsims** [comment]
@edgrosvenor okay I’ll leave the last one for you then! Is that everything you need from me on this?

**Comment by edgrosvenor** [comment]
@ashleighsims Nope. I've just added a test to make sure your logic works and that it didn't break the default redirect. Works beautifully. I'm merging it into master now. I really appreciate your help on this.

**Comment by ashleighsims** [comment]
@edgrosvenor No worries, glad to be of help. One thing I forgot is the updating of the README. Just wanted to add a note so you didn't forget.

**Comment by edgrosvenor** [comment]
@ashleighsims Thanks. I knew we hadn't updated the docs. @innoflash is working on a trait that will also need to be documented. So once that's working I'll fill in some missing tests and update the docs.

**Pull request merged**
