### PR TITLE
Change default user

### PR DESCRIPTION
**Pull request by innoflash**
How about we set the default user model to the one set as default in the `auth.providers.model` of the Laravel app.

Its not always `App/User`. Most developers are using a Models dir to keep models. I think picking it from the app makes it more flexible

### CODE REVIEW

**Comment by innoflash** [comment]
Just a note, i am yet to be introduced to the world of tests so the current changes passed the first 3 tests and i didnt know what to do with the rest :)

Cheers

**Comment by edgrosvenor** [comment]
I think I'd like to explore a different solution here. Now that we're verifying that the model we're working with is authenticatable, why don't we eliminate this configuration option altogether and find a way to encode the class name of the model into the link. That way this can work with any user-type model even multiple per site.

I'm going to leave this open for the moment because I haven't fully thought through the alternative I laid out above.

**Comment by innoflash** [comment]
Yeah you are right there, yesterday i was thinking of a use case and how do you think we can solve it here.

Imagine we have a company like a Retail shop with a setup like this one.
#### Admin
One who delegates tasks to the rest of the employees

#### Till Operators
Who used their ID card numbers

#### Supervisors
Who use their emails

So say the 3 belong to different tables and lets focus mainly on the last 2. So it means if we are to add these guys into the `auth.php` they will use different models and guards

Now suppose we wanna give them access to certain pieces of the system using our signed URLs how are we gonna separate them given there could be need to authenticate them on different parts. 

The till operators should use only till related functions (probably via a guard) and the supervisors are doing stock and other.

Can we use the magic here :)

**Comment by innoflash** [comment]
> Now that we're verifying that the model we're working with is authenticatable

I think by default the `Auth facade` uses the `Authenticatable` so even if we remove the check Laravel auto does that for us

**Pull request closed without merging**
