### PR TITLE
#30 Fix link never expiring 

### PR DESCRIPTION
**Pull request by kamiben**
Remove expires from the path to implicitly set is as a parameter

### CODE REVIEW

**Comment by edgrosvenor** [comment]
@kamiben Thank you. This fix is causing the tests to fail because the $expires parameter is expected to be in the url in the test set up `list($route, $expires, $uid) = explode('/', ltrim(parse_url($this->url)['path'], '/'));` around line 46 of SignedUrlTest.php.

Other than that, I think I'm ok with the PR. The only thing I'm not sure of is why the test in `public function an_expired_request_will_not_log_user_in()` passes. It sets the expiration timestamp back by an hour and at least in the test, it results in a 401 and the user is not logged in. So it appears that the behavior is ok as the package is originally written. Is there something wrong in that test? I just want to make sure that the fix is actually fixing something that's really broken and that the new method works and is demonstrated to be effective in testing.

**Comment by kamiben** [comment]
I will try to update the test so it gets expiration as a parameter. 

The test `an_expired_request_will_not_log_user_in()` actually passes because the test is  changing the expires parameter, which invalidates the signature (the signature being a hash of all parameters) so as you change the expire parameter, the signature becomes invalid.

As it is, the tests verifies that if the link was tampered with, it won't work, not if the expiration works. I don't really know how we could actually test for a real expiration case (maybe include some kind of wait so the link really expires, or a link validity of one or zero second on creation)

**Comment by kamiben** [comment]
I have updated the tests so they pass.
By reducing the link validity duration and moving the expiration at the end with a small wait, we can test for link expiration.
I think we should be good for this PR, what do you think ?

**Comment by edgrosvenor** [comment]
@kamiben Great PR! Thank you for catching and fixing this!

**Pull request merged**
