### PR TITLE
Add LPL_INVALID_SIGNATURE_MESSAGE to allow to customize the error message on invalid signature

### PR DESCRIPTION
**Pull request by kamiben**
Sorry about all the commits I don't really know how the previous commit got into the history.
Only two files are changed to allow this evolution.

### CODE REVIEW

**Comment by kamiben** [comment]
#29

**Comment by edgrosvenor** [comment]
@kamiben I merged another PR before yours and it's caused some conflicts. I can't push to your fork so I can't resolve them. Can you rebase and resolve the conflicts? Other than that the PR looks good. And don't worry going forward about CI stuff. I just do a StyleCI PR at the very end.

**Comment by edgrosvenor** [comment]
@kamiben Don't worry about it. I pulled in your work from your repo, created a fresh branch here, and merged it in. So this is merged but in a weird sort of way. The way I normally do things isn't working well today.

**Comment by kamiben** [comment]
@edgrosvenor Thanks ! Sorry for the mess ;)

**Pull request closed without merging**
