### PR TITLE
Fixed and optimized login method

### PR DESCRIPTION
**Pull request by musapinar**
- Fixed missing ```config()``` for ```remember``` parameter.
- optimized authentication

Reference: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Contracts/Auth/StatefulGuard.php#L40

### CODE REVIEW

**Comment by edgrosvenor** [comment]
@innoflash Do you suppose this fixes the issue you identified?

**Comment by edgrosvenor** [comment]
@musapinar Thank you! What I'm not sure of is using loginUsingId() as opposed to login() since one of the issues we're trying to address is having to define in advance what user model we're working with. @innoflash brought up a good point that sometimes sites will have multiple authenticatable models. I'm not sure how loginUsingId() handles that, whereas login() appears to work with whatever authenticable object you use. If you have a different understanding of this than we do, let me know.

**Comment by innoflash** [comment]
> @innoflash Do you suppose this fixes the issue you identified?

I don't know where i could be getting it wrong but this method did not solve my issue too

**Comment by musapinar** [comment]
https://github.com/laravel/framework/blob/7.x/src/Illuminate/Auth/SessionGuard.php#L401

where ```provider``` is https://github.com/laravel/framework/blob/7.x/src/Illuminate/Auth/EloquentUserProvider.php#L46

which then asks your ```config``` at https://github.com/laravel/framework/blob/7.x/src/Illuminate/Auth/CreatesUserProviders.php#L54

Why would one require your package to handle something that is out of your scope and already handled by Laravel?

This commit does not address any issue. I just came across this package via Laravel-News, browsed the src, and noticed this bug.

**Comment by innoflash** [comment]
Wassup buddy, this method works as well. We been having issues with some other staff not auth related. Thanks for this one

**Pull request closed without merging**
